# Generated by Django 6.1.1 on 2026-09-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stomat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
