# Generated by Django 6.1.1 on 2026-09-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stomat', '0003_alter_doctors_options_doctors_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='stomat/image/'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='qualification',
            field=models.ImageField(blank=True, null=True, upload_to='stomat/image'),
        ),
    ]
