# Generated by Django 6.1.1 on 2026-09-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stomat', '0006_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['name'], 'verbose_name': 'Услуга(цена)', 'verbose_name_plural': 'Услуги(цена)'},
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
