# Generated by Django 6.1.1 on 2026-10-01 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stomat', '0008_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
