# Generated by Django 6.1.1 on 2026-10-01 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stomat', '0009_remove_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='stomat/image/')),
            ],
        ),
        migrations.AlterField(
            model_name='doctors',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='stomat.doctorsphoto'),
        ),
    ]
