# Generated by Django 6.1.1 on 2026-10-01 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stomat', '0010_doctorsphoto_alter_doctors_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stomat/image/')),
            ],
        ),
        migrations.AlterField(
            model_name='doctors',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='stomat/image'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='stomat.doctorsqualification'),
        ),
        migrations.DeleteModel(
            name='DoctorsPhoto',
        ),
    ]
