# Generated by Django 6.1.1 on 2026-10-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stomat', '0011_doctorsqualification_alter_doctors_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsqualification',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
