# Generated by Django 6.1.1 on 2026-10-01 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stomat', '0012_doctorsqualification_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='qualification',
        ),
        migrations.AlterField(
            model_name='doctorsqualification',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorsQualification', to='stomat.doctors'),
        ),
    ]
