# Generated by Django 6.1.1 on 2026-10-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stomat', '0013_remove_doctors_qualification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.PositiveIntegerField()),
                ('data', models.DateField()),
                ('data_is_stock', models.BooleanField(default=False)),
                ('time', models.TimeField()),
                ('time_is_stock', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='doctors',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
